apiVersion: v1
kind: Service
metadata:  
  name: "clinic-app-service"
spec:
  type: NodePort
  selector:
    app: clinic-app
  ports:    
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80