apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-deployment
  labels:
    app: clinic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-app
  template:
    metadata:
      labels:
        app: clinic-app
    spec:
      containers:
      - name: clinic-app
        image: "milinddocker/clinic:1.2.4-152-SNAPSHOT"
        ports:
        - containerPort: 8082
        env:
        - name: DB_USER
          value: root
        - name: DB_HOST
          value: mysql
        - name: DB_PASSWORD
          value: root
      imagePullSecrets:
        - name: regcred
