apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1.2.4-129-SNAPSHOT-deployment
  labels:
    app: 1.2.4-129-SNAPSHOT-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1.2.4-129-SNAPSHOT-app
  template:
    metadata:
      labels:
        app: 1.2.4-129-SNAPSHOT-app
    spec:
      containers:
      - name: 1.2.4-129-SNAPSHOT-app
        image: "milinddocker/1.2.4-129-SNAPSHOT1.2.4-125-SNAPSHOT"
        ports:
        - containerPort: 8082
        env:
        - name: DB_USER
          value: root
        - name: DB_HOST
          value: mysql
        - name: DB_PASSWORD
          value: root
      imagePullSecrets:
        - name: regcred
