apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clinic-application
  namespace: default
spec:
  project: default

  source:
    repoURL: https://github.com/milinddevops/clinic.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true    